name: Workflow for creating and using an artifact

on:
 push

jobs:
 create:
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v4
   - name: Create file
     run: echo "Hello World" > file.txt
   - name: Upload artifact
     uses: actions/upload-artifact@v4
     with:
      name: file
      path: file.txt

  print:
   runs-on: ubuntu-latest
   needs: create
   steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
       name: file
       path: .
    - name: Print artifact
      run: cat file.txt